#include <array>
#include <cstdint>

#ifndef TRANSACTION_H
#define TRANSACTION_H

// using 32 random generated bytes for the wallet addresses
using uint256 = std::array<std::int8_t, 32>;

class CTransaction {
    public:
        CTransaction();
        ~CTransaction();

    private:
    int m_txID;
    uint256 m_senderAddr;
    uint256 m_recipientAddr;
    float m_amount;
};

#endif